// Builds a spoken sale confirmation for any amount out of pre-recorded segments
// (public/audio/seg/<lang>/<key>.mp3, generated by scripts/make_audio.py; keys must match SEGMENTS there).
// Kept free of imports so `node --test` can load it directly.

export type SaleMeta = { kind: "sale_confirmation"; amount: number; kg: number; material: string; credits: number };

const MATERIALS = ["plastic", "cardboard", "metal", "paper", "wire", "glass"];

export const segUrl = (lang: "hi" | "en", key: string) => `/audio/seg/${lang}/${key}.mp3`;

function hiNumber(n: number): string[] {
  if (n === 0) return ["w-shunya"];
  const out: string[] = [];
  const th = Math.floor(n / 1000);
  const h = Math.floor((n % 1000) / 100);
  const r = n % 100;
  if (th) out.push(`n-${th}`, "w-hazaar");
  if (h) out.push(`n-${h}`, "w-sau");
  if (r) out.push(`n-${r}`);
  return out;
}

function enBelow100(n: number): string[] {
  if (n < 20) return [`n-${n}`];
  const ones = n % 10;
  return ones ? [`n-${n - ones}`, `n-${ones}`] : [`n-${n}`];
}

function enNumber(n: number): string[] {
  if (n === 0) return ["w-zero"];
  const out: string[] = [];
  const th = Math.floor(n / 1000);
  const h = Math.floor((n % 1000) / 100);
  const r = n % 100;
  if (th) out.push(...enBelow100(th), "w-thousand");
  if (h) out.push(`n-${h}`, "w-hundred");
  if (r) out.push(...enBelow100(r));
  return out;
}

/** Segment keys for "₹A received · K kg material · C credits", or null if we can't voice it. */
export function composeSaleConfirmation(lang: "hi" | "en", m: SaleMeta): string[] | null {
  const amount = Math.round(m.amount);
  const tenths = Math.round(m.kg * 10);
  const kgInt = Math.floor(tenths / 10);
  const kgDec = tenths % 10;
  if (amount < 0 || amount >= 100_000 || kgInt >= 100_000 || m.credits < 0 || m.credits >= 100_000) return null;
  if (!MATERIALS.includes(m.material)) return null;
  const num = lang === "hi" ? hiNumber : enNumber;

  if (lang === "hi") {
    return [
      ...num(amount), "w-rupaye-mile",
      ...num(kgInt), ...(kgDec ? ["w-dashamlav", `n-${kgDec}`] : []), "w-kilo", `m-${m.material}`,
      "w-khaate-mein", ...num(m.credits), "w-credit-jude",
    ];
  }
  return [
    ...num(amount), "w-rupees-received",
    ...num(kgInt), ...(kgDec ? ["w-point", `n-${kgDec}`] : []), "w-kilos-of", `m-${m.material}`,
    ...num(m.credits), "w-credits-added",
  ];
}
